### ISSUE TITLE
permission denied on docker command execution

### ISSUE THREAD

**Issue by tmvenkadesh** [open-source-labs/Docketeer#100]
Hi Team, very thankful for this application, i am just facing issue that "permission denied" while executing docker commands, however when i added "sudo" in front of docker command in source code it is start working, is there any way to run command without sudo in source code.

**Comment by austinandrews** [comment]
This is an issue with Docker, rather than Docketeer. You can solve this problem by creating a Unix group to connect with the Docker daemon. See here: https://docs.docker.com/engine/install/linux-postinstall/

@lunaf-github, let me know if I'm missing anything else otherwise I will close this issue.
