### ISSUE TITLE
Docker compose functionality is broken.

### ISSUE THREAD

**Issue by austinandrews** [open-source-labs/Docketeer#105]
**Describe the bug**
When the docker compose tab is used to spin up multi-container networks/applications, the UI does not accurately portray the currently running containers nor does it enable the user to stop desired containers.

**To Reproduce**
1. Go to Docker Compose tab.
2. Specify a .yml file to compose.
3. Specify another .yml file to compose.
4. Note that only one container has a compose down button.
5. Click the compose down button.
6. Compare the UI to what is returned by `docker ps`. 

**Expected behavior**
All composed containers should have a compose down button and the UI should list all and only the containers that are actually running (i.e. there should not be discrepancies with what is returned by `docker ps`.

**Comment by errc-lee** [comment]
Docketeer 9.0+ please confirm whether this issue still exists.

**Comment by austinandrews** [comment]
With the exception of the file extension, `src/redux/reducers/dockerComposeReducer.ts` is unchanged since 6.0.0. So it's very unlikely that this bug has been fixed (haven't run the new app so feel free to correct me if I'm wrong).

**Comment by mimi0j** [comment]
Hi Austen, the docker compose buttons were rendered obsolete in a previous iteration, most likely due to this error. The `src/redux/reducers/dockerComposeReducer.ts` file is still there, so we hope a new iteration can bring that functionality back!
