### ISSUE TITLE
Two dockerfiles in root causes collision when repository is cloned

### ISSUE THREAD

**Issue by austinandrews** [open-source-labs/Docketeer#133]
There are two dockerfiles, one named `dockerfile`, the other named `Dockerfile`. This fact causes a collision when the repository is cloned:

`warning: the following paths have collided (e.g. case-sensitive paths
on a case-insensitive filesystem) and only one from the same
colliding group is in the working tree:

  'Dockerfile'
  'dockerfile'`
  
I'm not sure what the resolution mechanism is here but my clone of the repo ended up with `dockerfile`, not `Dockerfile`.

**Comment by d-hp** [comment]
Hey Austin,

Thank you for bringing this to my attention. I'm not exactly sure how this happened but I've removed `Dockerfile` and kept `dockerfile` within the root directory. Users should now be able to clone the repository without receiving the stated warning. I apologize for the time that it took for me to get back to you & thank you again for all your advice.
