### ISSUE TITLE
A few website issues when viewing on a 24" monitor:

### ISSUE THREAD

**Issue by Schmang13** [open-source-labs/Docketeer#152]
When viewing the website, I realized there were a couple of scaling/positioning issues when being viewed on a 24" monitor:

-Header options are shifted to the right and you need to scroll over to access them.
         -Would be best if these options were right justified so there was no need to scroll to the right.
-Hard to read the text on the main page due to the font color being pretty close to the background colors.
         -Change text color or background color to increase contrast for easier visibility.

**Comment by mimi0j** [comment]
Hi Matthew, we have moved our website to docketeer.io! It is fully responsive and mobile friendly.
