### ISSUE TITLE
Setup step 2.5 on Readme

### ISSUE THREAD

**Issue by lunaf-github** [open-source-labs/Docketeer#158]
**Describe the bug**
To set up the Kubernetes cluster it directs to user to go to http://localhost:4001/api/k8. 

This link does not work. It should be http://localhost:4000/api/k8.

**Comment by jaenixlee** [comment]
Hi Fernando,

If you run the steps in the README in order, the port for the setup application should switch to 4001 once you run `npm run dev`. 
I have just tested it again and the URL in the README is working correctly - please let me know if you still get this issue!
