### ISSUE TITLE
Module not found: Error: Can't resolve 'babel-loader'

### ISSUE THREAD

**Issue by NiketanG** [open-source-labs/Docketeer#78]
Bug:
Getting the following error when running the app with `yarn dev`, 

Module not found: Error: Can't resolve 'babel-loader'

The issue is resolved when adding babel-loader as a devDependency using the following command:
`yarn add -D babel-loader`

1. Clone the repo
2. Install dependencies `yarn`
3. Run: `yarn dev`
Module not found: Error: Can't resolve 'babel-loader'

**Desktop (please complete the following information):**
 - OS: Fedora 33
 - Browser Google Chrome Latest

Solution:
Add Babel-Loader in package.json

**Comment by errc-lee** [comment]
Issue has been resolved, thank you.
